-- Synthetic fixture shaped to the supplied PostgreSQL 17 schema report.
-- The four original RPC definitions below are schema metadata, not user records.
CREATE ROLE anon;
CREATE ROLE authenticated;
CREATE ROLE service_role BYPASSRLS;
CREATE SCHEMA auth;
GRANT USAGE ON SCHEMA public, auth TO anon, authenticated, service_role;
-- Reproduce Supabase's permissive default grants to test explicit revocations.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON FUNCTIONS TO anon, authenticated, service_role;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$
    SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;
CREATE TABLE auth.users (id uuid PRIMARY KEY, email text, created_at timestamptz DEFAULT now());
CREATE TABLE public.users (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username text, first_name text, middle_name text, last_name text,
    phone_number text, address text, avatar_url text, blood_type text,
    allergies text, emergency_contact1_name text, emergency_contact1_phone text,
    status text DEFAULT 'active'
);
CREATE TABLE public.admin_roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz NOT NULL DEFAULT now(),
    user_id uuid DEFAULT gen_random_uuid() REFERENCES auth.users(id)
);
ALTER TABLE auth.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can insert own profile" ON public.users FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.users FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can view own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Enable read access for all users" ON public.admin_roles FOR SELECT USING (true);
CREATE OR REPLACE FUNCTION public.admin_delete_user(target_user_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Deleting from auth.users will automatically cascade and delete the public.users row
  DELETE FROM auth.users WHERE id = target_user_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_toggle_suspend_user(target_user_id uuid, new_status text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  UPDATE public.users SET status = new_status WHERE id = target_user_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_update_user(target_user_id uuid, update_data jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  UPDATE public.users
  SET
    first_name = update_data->>'first_name',
    last_name = update_data->>'last_name',
    phone_number = update_data->>'phone_number',
    address = update_data->>'address'
  WHERE id = target_user_id;
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_all_users_with_roles()
 RETURNS TABLE(id uuid, email text, username text, first_name text, middle_name text, last_name text, phone_number text, address text, avatar_url text, blood_type text, allergies text, emergency_contact1_name text, emergency_contact1_phone text, created_at timestamp with time zone, role text)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN QUERY
  SELECT
    au.id,
    au.email::text,
    u.username,
    u.first_name,
    u.middle_name,
    u.last_name,
    u.phone_number,
    u.address,
    u.avatar_url,
    u.blood_type,
    u.allergies,
    u.emergency_contact1_name,
    u.emergency_contact1_phone,
    au.created_at,
    CASE WHEN ar.user_id IS NOT NULL THEN 'admin' ELSE 'user' END AS role
  FROM auth.users au
  LEFT JOIN public.users u ON au.id::text = u.id::text
  LEFT JOIN public.admin_roles ar ON au.id::text = ar.user_id::text;
END;
$function$;
